//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXDevHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXDevHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes.
        /// </summary>
        internal static string AllChangesSection {
            get {
                return ResourceManager.GetString("AllChangesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In Status.
        /// </summary>
        internal static string checkInCommentTitle {
            get {
                return ResourceManager.GetString("checkInCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {solution} ({status}).
        /// </summary>
        internal static string defaultCheckInComment {
            get {
                return ResourceManager.GetString("defaultCheckInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--End: Work item: {workitem}.
        /// </summary>
        internal static string EndTag {
            get {
                return ResourceManager.GetString("EndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in the work item id for one or more work items that you intend to make changes for. Separate the id&apos;s with a comma sign..
        /// </summary>
        internal static string informationString {
            get {
                return ResourceManager.GetString("informationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Tag.
        /// </summary>
        internal static string InsertCodeTag {
            get {
                return ResourceManager.GetString("InsertCodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event {0} could not be logged, restart Visual Studio.
        /// </summary>
        internal static string logMessage {
            get {
                return ResourceManager.GetString("logMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Changes.
        /// </summary>
        internal static string MyChangesSection {
            get {
                return ResourceManager.GetString("MyChangesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tags are not setup or not found, check the tools/Options menu.
        /// </summary>
        internal static string notConfigured {
            get {
                return ResourceManager.GetString("notConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a work item id.
        /// </summary>
        internal static string NoWIT {
            get {
                return ResourceManager.GetString("NoWIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a work item as the item to tag your code and check in comments with..
        /// </summary>
        internal static string noWorkItemSelected {
            get {
                return ResourceManager.GetString("noWorkItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Changes.
        /// </summary>
        internal static string RecentChangesPage {
            get {
                return ResourceManager.GetString("RecentChangesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reflect PendingChangesPage {0}.
        /// </summary>
        internal static string reflectionPendingChangesFail {
            get {
                return ResourceManager.GetString("reflectionPendingChangesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event source xpp developer must be registred, in order to do that start Visual Studio run with the administrator privilege level (you need to do that if you run AX7 development too).
        /// </summary>
        internal static string registerEventSource {
            get {
                return ResourceManager.GetString("registerEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SampleImage {
            get {
                object obj = ResourceManager.GetObject("SampleImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Selected Word.
        /// </summary>
        internal static string selectedWordDisplayName {
            get {
                return ResourceManager.GetString("selectedWordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Work Item.
        /// </summary>
        internal static string selectWIT {
            get {
                return ResourceManager.GetString("selectWIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xppDev.
        /// </summary>
        internal static string Settingfolder {
            get {
                return ResourceManager.GetString("Settingfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \xppDevHelper.set.
        /// </summary>
        internal static string Settingsfile {
            get {
                return ResourceManager.GetString("Settingsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //++Start: Work item: {workitem} Project: {project} {lb}Developer: {developer} Date: {date}.
        /// </summary>
        internal static string StartTag {
            get {
                return ResourceManager.GetString("StartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} Type in the work item id for one or more work items that you intend to make changes for. Separate the id&apos;s with a comma sign. .
        /// </summary>
        internal static string updatedInformationString {
            get {
                return ResourceManager.GetString("updatedInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudio.DTE.14.0.
        /// </summary>
        internal static string VisualStudio {
            get {
                return ResourceManager.GetString("VisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Changes.
        /// </summary>
        internal static string xppDev {
            get {
                return ResourceManager.GetString("xppDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPP Developer - Error.
        /// </summary>
        internal static string xppDevErrorTitle {
            get {
                return ResourceManager.GetString("xppDevErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPP Developer.
        /// </summary>
        internal static string xppDevEventLog {
            get {
                return ResourceManager.GetString("xppDevEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPP Developer Eventlog.
        /// </summary>
        internal static string xppDevEventLogName {
            get {
                return ResourceManager.GetString("xppDevEventLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/XppDevs.
        /// </summary>
        internal static string xppDevHomePage {
            get {
                return ResourceManager.GetString("xppDevHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XppDevs_Logo_200 {
            get {
                object obj = ResourceManager.GetObject("XppDevs_Logo_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XppDevs_Logo_48x48 {
            get {
                object obj = ResourceManager.GetObject("XppDevs-Logo-48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your settings, the settings for the xpp Dev helper appliction is not setup.
        /// </summary>
        internal static string xppNoSettings {
            get {
                return ResourceManager.GetString("xppNoSettings", resourceCulture);
            }
        }
    }
}
